#!/usr/bin/env bun
import { $ } from 'bun';
import { basename } from 'node:path';
import { CONFIG_PATHS, ENV_KEYS, OPTIONAL_WORKER_SECRETS, loadConfig, serializeConfig } from './lib/wrangler-config';

/**
 * Single deploy path for local machines and CI.
 *
 * Generates wrangler.deploy.jsonc from the committed wrangler.jsonc with real
 * KV and D1 IDs injected from the environment (GitHub Actions secrets in CI;
 * bun auto-loads .env.local locally), applies D1 migrations, runs
 * `wrangler deploy` against the generated file, and syncs the optional
 * worker secrets (ACCESS_KEY) when present in the environment. The committed
 * config never holds real IDs.
 *
 * Flags:
 *   --generate-only   write wrangler.deploy.jsonc and exit (placeholders pass
 *                     through when the environment has no IDs, so fork PRs
 *                     can still dry-run builds)
 *   --dry-run         generate, then `wrangler deploy --dry-run`
 */
type Mode = 'deploy' | 'dry-run' | 'generate-only';

function resolveMode(argv: readonly string[]): Mode {
  if (argv.includes('--generate-only')) return 'generate-only';
  if (argv.includes('--dry-run')) return 'dry-run';
  return 'deploy';
}

async function generateDeployConfig(mode: Mode): Promise<void> {
  const config = await loadConfig();
  const namespace = config.kv_namespaces?.[0];
  const database = config.d1_databases?.[0];
  if (!namespace || !database) {
    console.error(`Missing kv_namespaces or d1_databases entry in ${basename(CONFIG_PATHS.source)}`);
    process.exit(1);
  }

  const kvId = process.env[ENV_KEYS.kvId];
  const kvPreviewId = process.env[ENV_KEYS.kvPreviewId] ?? kvId;
  const d1Id = process.env[ENV_KEYS.d1Id];

  if (
    kvId !== undefined &&
    kvId !== '' &&
    kvPreviewId !== undefined &&
    kvPreviewId !== '' &&
    d1Id !== undefined &&
    d1Id !== ''
  ) {
    namespace.id = kvId;
    namespace.preview_id = kvPreviewId;
    database.database_id = d1Id;
    console.log('Injected KV namespace and D1 database IDs from environment.');
  } else if (mode === 'deploy') {
    console.error(
      `${ENV_KEYS.kvId} and/or ${ENV_KEYS.d1Id} are not set. Run \`bun run setup\` first, or set them in the environment.`,
    );
    process.exit(1);
  } else {
    console.log('No resource IDs in environment; keeping placeholders.');
  }

  // The custom domain is per-deployment (your own domain, never hardcoded
  // in the committed config). When CUSTOM_DOMAIN is set, attach it; when
  // absent, the worker keeps only its workers.dev URL.
  const customDomain = process.env[ENV_KEYS.customDomain];
  if (customDomain !== undefined && customDomain !== '') {
    config.routes = [{ pattern: customDomain, custom_domain: true }];
    console.log(`Injected custom domain ${customDomain} from environment.`);
  }

  const header = `// Auto-generated by scripts/${basename(import.meta.filename)}. Do not edit.\n`;
  await Bun.write(CONFIG_PATHS.deploy, header + serializeConfig(config));
  console.log(`Wrote ${CONFIG_PATHS.deploy}`);
}

async function main(): Promise<void> {
  const mode = resolveMode(process.argv);
  await generateDeployConfig(mode);
  if (mode === 'generate-only') return;

  const deployArgs = mode === 'dry-run' ? ['--dry-run'] : [];
  if (mode !== 'dry-run') {
    console.log('Applying D1 migrations…');
    await $`bun x wrangler d1 migrations apply AUDIT_DB --remote --config ${CONFIG_PATHS.deploy}`;
  }
  await $`bun x wrangler deploy --config ${CONFIG_PATHS.deploy} ${deployArgs}`;
  if (mode === 'dry-run') return;

  for (const secretName of OPTIONAL_WORKER_SECRETS) {
    const value = process.env[secretName];
    if (value !== undefined && value !== '') {
      console.log(`Syncing ${secretName} worker secret…`);
      await $`bun x wrangler secret put ${secretName} --config ${CONFIG_PATHS.deploy} < ${new Response(value)}`;
    } else {
      console.log(`${secretName} not in environment; skipping secret sync.`);
    }
  }
}

await main();
